spring.application.name=discordclone

spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/discordclone
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

app.jwt.secret=change-this-dev-secret-please-change-this-dev-secret
app.jwt.expiration-minutes=1440

server.port=8080
